language: python
env:
  - PYTHON=python PYSUF=''
# command to install dependencies
before_install:
   - sudo apt-get install python-numpy
   - sudo apt-get install python-gdal
   - sudo apt-get install python-nose
install:
   - pip install . --use-mirrors
# command to run tests
script: nosetests -A 'not slow' -v safe --stop
